In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.svm import LinearSVC
from scipy.linalg import khatri_rao
from matplotlib import pyplot as plt
import time as t
import random

In [ ]:
y = np.array([1,0,0,1,0,1])
print(y)
y_new = 2*y
print(y_new)
y_last = (1-y_new)
print(y_last)

[1 0 0 1 0 1]
[2 0 0 2 0 2]
[-1  1  1 -1  1 -1]


In [ ]:
data = np.loadtxt( "/content/train.dat" )
data.shape

(10000, 9)

In [ ]:
y = data[:,-1]
print(y.shape)

(10000,)


In [ ]:
def createFeatures( X ):
    return np.cumprod( np.flip( 2 * X - 1 , axis = 1 ), axis = 1 )

data_trn, data_tst = train_test_split( data, train_size = 8000 )

X_raw = data_trn[:,:-1]
X = createFeatures( X_raw )
y = data_trn[:,-1]

y = np.where( y > 0, 1, -1 )

X_t_raw = data_tst[:,:-1]
X_t = createFeatures( X_t_raw )
y_t = data_tst[:,-1]

y_t = np.where( y_t > 0, 1, -1 )

clf = LinearSVC( loss = "hinge" )
clf.fit( X, y )
np.average( y_t == clf.predict( X_t ) )

0.671

In [ ]:
def createFeatures( X ):
    return np.cumprod( np.flip(1 - 2*X , axis = 1 ), axis = 1 )

In [ ]:
X_t = createFeatures(data[:,:-1])
Y_t = data[:,-1]
print(X_t.shape,Y_t.shape)

(10000, 8) (10000,)


In [ ]:
bias = np.array([1 for i in range(X_t.shape[0])])
print(bias.shape)

(10000,)


In [ ]:
X_t = np.c_[X_t,bias]
print(X_t.shape)
print(X_t[0])

(10000, 9)
[ 1.  1. -1. -1. -1. -1. -1. -1.  1.]


In [ ]:
fin_Xt = khatri_rao(X_t.T,X_t.T)
fin_Xt = khatri_rao(fin_Xt,X_t.T)
print(fin_Xt.shape)

(729, 10000)


In [ ]:
def get_renamed_labels(y):
  y_new = 2*y
  y_new = (1-y_new)
  return y_new

In [ ]:
fin_Yt = get_renamed_labels(Y_t)
print(Y_t)
print(fin_Yt)

[1. 0. 1. ... 1. 1. 1.]
[-1.  1. -1. ... -1. -1. -1.]


In [ ]:
print(fin_Xt.shape,fin_Yt.shape)

(729, 10000) (10000,)


In [ ]:
n = 500
X = fin_Xt.T
y = fin_Yt
C = 1
neta = 1
epochs = 10
print(X.shape)
print(y.shape)

(10000, 729)
(10000,)


In [ ]:
g = np.zeros( (9,) )
print(g.shape)
print(g)
g[5 < 1] = -1
print(g)

(9,)
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
def getCSVMObjVal( theta ):
    w = theta[0:-1]
    b = theta[-1]
    hingeLoss = np.maximum( 1 - np.multiply( (X.dot( w ) + b), y ), 0 )
    return 0.5 * w.dot( w ) + C * np.sum( hingeLoss )

In [ ]:
theta = X
w = theta[0:-1]
b = theta[-1]
print(w.shape)
print(b.shape)

(9999, 729)
(729,)


In [ ]:
def getCSVMGrad( theta,w ):
    discriminant = np.multiply( (X.dot( w )), y )
    g = np.zeros( (y.size,) )
    g[discriminant < 1] = -1
    #delb = C * g.dot( y )
    delw = w + C * (X.T * g).dot( y )
    return np.array(delw)

In [ ]:
w = np.ones((X.shape[1],))
print(w.shape)

(729,)


In [ ]:
delw = np.array((getCSVMGrad(X,w)))
print(delw.shape)

(729,)


In [ ]:
from tqdm import tqdm

In [ ]:
epochs = 1000
C = 1
neta = 0.001

In [ ]:
def applySVM(X,w):
  return X.dot(w)

In [ ]:
X_trn = np.flip(createFeatures(data_trn[:,:-1]))
bias = np.array([1 for i in range(X_trn.shape[0])])
Y_trn = data_trn[:,-1]
X_trn = np.c_[X_trn,bias]
Y_trn = get_renamed_labels(Y_trn)
fin_Xt = khatri_rao(X_trn.T,X_trn.T)
X_trn = khatri_rao(fin_Xt,X_trn.T)
X_trn = X_trn.T
print(X_trn.shape,Y_trn.shape)

(8000, 729) (8000,)


In [ ]:
w = np.zeros((X.shape[1],))
maxx = 0
epoch = 0
for i in tqdm(range(epochs)):
  delw = getCSVMGrad(X,w)
  w = w - neta*(delw)
  y_t_pred = applySVM(X,w)
  y_t_pred = np.where( y_t_pred > 0, 1, -1 )
  av = np.average( y == y_t_pred )
  print(av)
  if av > maxx:
    epoch = i
    maxx = av
print(maxx)

  0%|          | 3/1000 [00:00<00:40, 24.84it/s]

0.8056
0.8526
0.8862
0.8946


  1%|          | 6/1000 [00:00<00:37, 26.17it/s]

0.8975
0.8898


  1%|          | 9/1000 [00:00<00:37, 26.77it/s]

0.9199
0.9137
0.9223
0.8943


  1%|          | 12/1000 [00:00<00:38, 25.99it/s]

0.8714
0.8924


  2%|▏         | 15/1000 [00:00<00:37, 26.44it/s]

0.9162
0.92
0.9358
0.9301


  2%|▏         | 18/1000 [00:00<00:36, 26.63it/s]

0.938
0.9395


  2%|▏         | 21/1000 [00:00<00:36, 26.84it/s]

0.9402
0.9347
0.909
0.8874


  2%|▏         | 24/1000 [00:00<00:36, 26.96it/s]

0.9153
0.925


  3%|▎         | 27/1000 [00:01<00:37, 26.18it/s]

0.9287
0.9209
0.9205
0.9441


  3%|▎         | 30/1000 [00:01<00:36, 26.60it/s]

0.9287
0.9108


  3%|▎         | 33/1000 [00:01<00:35, 26.89it/s]

0.9285
0.9492
0.9408
0.9352


  4%|▎         | 36/1000 [00:01<00:35, 26.99it/s]

0.9411
0.9433


  4%|▍         | 39/1000 [00:01<00:35, 27.11it/s]

0.9335
0.9331
0.9581
0.9534


  4%|▍         | 42/1000 [00:01<00:35, 27.17it/s]

0.9591
0.9626


  4%|▍         | 45/1000 [00:01<00:35, 27.16it/s]

0.9528
0.9338
0.9458
0.9384


  5%|▍         | 48/1000 [00:01<00:34, 27.23it/s]

0.9267
0.9217


  5%|▌         | 51/1000 [00:01<00:34, 27.23it/s]

0.9249
0.9426
0.9664
0.9818


  5%|▌         | 54/1000 [00:02<00:36, 26.27it/s]

0.9806
0.9849


  6%|▌         | 57/1000 [00:02<00:35, 26.39it/s]

0.9831
0.982
0.9835
0.9807


  6%|▌         | 60/1000 [00:02<00:36, 25.84it/s]

0.9666
0.9661


  6%|▋         | 63/1000 [00:02<00:35, 26.23it/s]

0.9749
0.9838
0.986
0.9848


  7%|▋         | 66/1000 [00:02<00:35, 26.45it/s]

0.9773
0.9745


  7%|▋         | 69/1000 [00:02<00:34, 26.61it/s]

0.9783
0.9631
0.9572
0.9531


  7%|▋         | 72/1000 [00:02<00:34, 26.68it/s]

0.9765
0.9733


  8%|▊         | 75/1000 [00:02<00:34, 26.85it/s]

0.963
0.9652
0.9579
0.9608


  8%|▊         | 78/1000 [00:02<00:34, 26.87it/s]

0.9434
0.9536
0.9491
0.9523


  8%|▊         | 81/1000 [00:03<00:39, 23.10it/s]

0.9696
0.9696


  8%|▊         | 84/1000 [00:03<00:45, 20.22it/s]

0.9679
0.9666


  9%|▊         | 87/1000 [00:03<00:43, 20.84it/s]

0.948
0.9538
0.9644
0.9755


  9%|▉         | 90/1000 [00:03<00:49, 18.53it/s]

0.9771
0.9786
0.9927


  9%|▉         | 93/1000 [00:03<00:46, 19.51it/s]

0.9773
0.9897


 10%|▉         | 96/1000 [00:03<00:46, 19.49it/s]

0.9862
0.9825
0.9755
0.9653
0.9699


 10%|▉         | 99/1000 [00:04<00:43, 20.61it/s]

0.9828
0.9853
0.9716


 10%|█         | 102/1000 [00:04<00:43, 20.65it/s]

0.9715
0.964


 10%|█         | 105/1000 [00:04<00:40, 21.94it/s]

0.967
0.9528
0.9665
0.9743


 11%|█         | 108/1000 [00:04<00:38, 23.22it/s]

0.9899
0.9833


 11%|█         | 111/1000 [00:04<00:36, 24.21it/s]

0.9631
0.9574
0.9349
0.955


 11%|█▏        | 114/1000 [00:04<00:35, 24.83it/s]

0.9662
0.965


 12%|█▏        | 117/1000 [00:04<00:34, 25.54it/s]

0.9636
0.9615
0.9849
0.9882


 12%|█▏        | 120/1000 [00:04<00:33, 25.92it/s]

0.9904
0.9967


 12%|█▏        | 123/1000 [00:04<00:33, 25.95it/s]

1.0
0.9967
0.9958
0.9974


 13%|█▎        | 126/1000 [00:05<00:33, 26.38it/s]

0.9963
0.9958


 13%|█▎        | 129/1000 [00:05<00:34, 25.46it/s]

0.9956
1.0
1.0
1.0


 13%|█▎        | 132/1000 [00:05<00:33, 26.22it/s]

1.0
1.0


 14%|█▎        | 135/1000 [00:05<00:32, 26.34it/s]

1.0
1.0
1.0
1.0


 14%|█▍        | 138/1000 [00:05<00:32, 26.72it/s]

1.0
1.0


 14%|█▍        | 141/1000 [00:05<00:32, 26.67it/s]

1.0
1.0
1.0
1.0


 14%|█▍        | 144/1000 [00:05<00:31, 27.01it/s]

1.0
1.0


 15%|█▍        | 147/1000 [00:05<00:31, 26.96it/s]

1.0
1.0
1.0


 15%|█▌        | 150/1000 [00:06<00:34, 24.77it/s]

1.0
1.0


 15%|█▌        | 153/1000 [00:06<00:33, 25.25it/s]

1.0
1.0
1.0
1.0


 16%|█▌        | 156/1000 [00:06<00:33, 24.97it/s]

1.0
1.0


 16%|█▌        | 159/1000 [00:06<00:33, 25.21it/s]

1.0
1.0
1.0
1.0


 16%|█▌        | 162/1000 [00:06<00:32, 25.40it/s]

1.0
1.0


 16%|█▋        | 165/1000 [00:06<00:32, 25.81it/s]

1.0
1.0
1.0
1.0


 17%|█▋        | 168/1000 [00:06<00:32, 25.53it/s]

1.0
1.0


 17%|█▋        | 171/1000 [00:06<00:31, 26.02it/s]

1.0
1.0
1.0
1.0


 17%|█▋        | 174/1000 [00:06<00:31, 26.16it/s]

1.0
1.0


 18%|█▊        | 177/1000 [00:07<00:31, 26.37it/s]

1.0
1.0
1.0
1.0


 18%|█▊        | 180/1000 [00:07<00:30, 26.73it/s]

1.0
1.0


 18%|█▊        | 183/1000 [00:07<00:32, 25.41it/s]

1.0
1.0
1.0
1.0
1.0


 19%|█▉        | 189/1000 [00:07<00:30, 26.53it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 20%|█▉        | 195/1000 [00:07<00:30, 26.48it/s]

1.0
1.0
1.0
1.0
1.0
1.0

 20%|██        | 201/1000 [00:07<00:30, 25.94it/s]


1.0
1.0
1.0
1.0
1.0


 21%|██        | 207/1000 [00:08<00:30, 26.34it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 21%|██        | 210/1000 [00:08<00:31, 25.21it/s]

1.0
1.0
1.0
1.0
1.0


 21%|██▏       | 213/1000 [00:08<00:30, 25.63it/s]

1.0


 22%|██▏       | 219/1000 [00:08<00:30, 25.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0

 22%|██▎       | 225/1000 [00:08<00:29, 25.95it/s]


1.0
1.0
1.0
1.0
1.0


 23%|██▎       | 231/1000 [00:09<00:29, 26.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 24%|██▎       | 237/1000 [00:09<00:29, 25.87it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 24%|██▍       | 243/1000 [00:09<00:28, 26.37it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 25%|██▍       | 249/1000 [00:09<00:27, 26.83it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 26%|██▌       | 255/1000 [00:10<00:27, 26.84it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 26%|██▌       | 261/1000 [00:10<00:27, 26.95it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 27%|██▋       | 267/1000 [00:10<00:27, 26.50it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 27%|██▋       | 273/1000 [00:10<00:27, 26.39it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 28%|██▊       | 279/1000 [00:10<00:27, 26.35it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 28%|██▊       | 285/1000 [00:11<00:26, 26.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 29%|██▉       | 288/1000 [00:11<00:32, 22.04it/s]

1.0
1.0
1.0
1.0


 29%|██▉       | 291/1000 [00:11<00:34, 20.64it/s]

1.0
1.0
1.0
1.0


 29%|██▉       | 294/1000 [00:11<00:36, 19.24it/s]

1.0
1.0
1.0


 30%|██▉       | 299/1000 [00:12<00:40, 17.18it/s]

1.0
1.0
1.0
1.0


 30%|███       | 302/1000 [00:12<00:40, 17.37it/s]

1.0
1.0
1.0


 31%|███       | 306/1000 [00:12<00:46, 15.01it/s]

1.0
1.0
1.0


 31%|███       | 310/1000 [00:12<00:44, 15.42it/s]

1.0
1.0
1.0
1.0


 31%|███▏      | 314/1000 [00:13<00:43, 15.80it/s]

1.0
1.0
1.0
1.0


 32%|███▏      | 316/1000 [00:13<00:46, 14.63it/s]

1.0
1.0
1.0


 32%|███▏      | 320/1000 [00:13<00:47, 14.22it/s]

1.0
1.0
1.0


 32%|███▏      | 322/1000 [00:13<00:51, 13.06it/s]

1.0
1.0
1.0


 33%|███▎      | 326/1000 [00:13<00:45, 14.93it/s]

1.0
1.0
1.0
1.0


 33%|███▎      | 330/1000 [00:14<00:42, 15.68it/s]

1.0
1.0
1.0
1.0


 33%|███▎      | 334/1000 [00:14<00:42, 15.86it/s]

1.0
1.0
1.0
1.0


 34%|███▍      | 338/1000 [00:14<00:39, 16.68it/s]

1.0
1.0
1.0
1.0


 34%|███▍      | 342/1000 [00:14<00:44, 14.73it/s]

1.0
1.0
1.0


 35%|███▍      | 346/1000 [00:15<00:41, 15.74it/s]

1.0
1.0
1.0
1.0


 35%|███▌      | 351/1000 [00:15<00:37, 17.29it/s]

1.0
1.0
1.0
1.0
1.0


 35%|███▌      | 353/1000 [00:15<00:43, 14.72it/s]

1.0
1.0
1.0


 36%|███▌      | 357/1000 [00:15<00:43, 14.73it/s]

1.0
1.0
1.0


 36%|███▌      | 359/1000 [00:16<00:48, 13.23it/s]

1.0
1.0
1.0
1.0


 36%|███▋      | 365/1000 [00:16<00:44, 14.25it/s]

1.0
1.0
1.0
1.0


 37%|███▋      | 367/1000 [00:16<00:47, 13.29it/s]

1.0
1.0
1.0


 37%|███▋      | 371/1000 [00:16<00:48, 12.98it/s]

1.0
1.0
1.0


 37%|███▋      | 373/1000 [00:17<00:48, 12.96it/s]

1.0
1.0
1.0
1.0

 38%|███▊      | 377/1000 [00:17<00:43, 14.35it/s]


1.0
1.0
1.0


 38%|███▊      | 381/1000 [00:17<00:42, 14.50it/s]

1.0
1.0
1.0


 38%|███▊      | 385/1000 [00:17<00:39, 15.44it/s]

1.0
1.0
1.0
1.0


 39%|███▉      | 389/1000 [00:18<00:40, 15.15it/s]

1.0
1.0
1.0
0.9874


 39%|███▉      | 393/1000 [00:18<00:40, 14.89it/s]

0.9691
0.9609
0.9622
0.9127


 40%|███▉      | 397/1000 [00:18<00:36, 16.71it/s]

0.8835
0.8766
0.8985
0.9217


 40%|████      | 401/1000 [00:18<00:35, 16.95it/s]

0.9363
0.9409
0.9459
0.9628


 40%|████      | 403/1000 [00:19<00:37, 15.82it/s]

0.9824
0.9733
0.9649


 41%|████      | 407/1000 [00:19<00:43, 13.73it/s]

0.9662
0.9603
0.9499


 41%|████      | 411/1000 [00:19<00:41, 14.17it/s]

0.9262
0.9171
0.9452
0.952


 42%|████▏     | 415/1000 [00:19<00:41, 13.93it/s]

0.9428
0.9314
0.9288
0.9477


 42%|████▏     | 417/1000 [00:20<00:41, 13.99it/s]

0.9796
0.9781
0.9666
0.9533


 42%|████▏     | 422/1000 [00:20<00:37, 15.48it/s]

0.9643
0.9819
0.9782


 42%|████▏     | 424/1000 [00:20<00:37, 15.20it/s]

0.9732
0.9866
0.9898


 43%|████▎     | 428/1000 [00:20<00:39, 14.36it/s]

0.9881
0.9886
0.9801
0.9723


 43%|████▎     | 432/1000 [00:21<00:41, 13.54it/s]

0.979
0.9887
0.9969


 43%|████▎     | 434/1000 [00:21<00:42, 13.37it/s]

0.9956
0.9889
0.9932


 44%|████▍     | 438/1000 [00:21<00:42, 13.11it/s]

0.9816
0.9764
0.978


 44%|████▍     | 440/1000 [00:21<00:49, 11.40it/s]

0.9855
0.9738


 44%|████▍     | 442/1000 [00:22<00:50, 11.10it/s]

0.972
0.9691
0.9647


 45%|████▍     | 446/1000 [00:22<00:41, 13.20it/s]

0.9724
0.9751
0.9774
0.9816


 45%|████▌     | 451/1000 [00:22<00:33, 16.31it/s]

0.9748
0.9744
0.9751
0.974


 46%|████▌     | 455/1000 [00:22<00:33, 16.35it/s]

0.9811
0.9834
0.9817
0.9754


 46%|████▌     | 459/1000 [00:23<00:34, 15.86it/s]

0.9819
0.9886
0.9877
0.9874


 46%|████▋     | 463/1000 [00:23<00:35, 15.26it/s]

0.9804
0.9832
0.9761
0.9848


 47%|████▋     | 467/1000 [00:23<00:34, 15.49it/s]

0.9958
0.9928
0.9846
0.9714


 47%|████▋     | 471/1000 [00:23<00:34, 15.23it/s]

0.9538
0.95
0.9327
0.9413


 48%|████▊     | 476/1000 [00:24<00:29, 17.96it/s]

0.9508
0.973
0.9855
0.9746
0.9806


 48%|████▊     | 479/1000 [00:24<00:28, 18.37it/s]

0.9816
0.994
1.0
1.0


 48%|████▊     | 483/1000 [00:24<00:29, 17.46it/s]

1.0
1.0
1.0


 48%|████▊     | 485/1000 [00:24<00:32, 15.62it/s]

1.0
1.0
1.0


 49%|████▉     | 489/1000 [00:24<00:38, 13.15it/s]

1.0
1.0
1.0


 49%|████▉     | 493/1000 [00:25<00:35, 14.40it/s]

1.0
1.0
1.0
1.0


 50%|████▉     | 495/1000 [00:25<00:36, 13.66it/s]

1.0
1.0
1.0
1.0

 50%|█████     | 500/1000 [00:25<00:29, 17.01it/s]


1.0
1.0
1.0
1.0
1.0


 51%|█████     | 506/1000 [00:25<00:24, 20.45it/s]

1.0
1.0
1.0
1.0
1.0


 51%|█████     | 512/1000 [00:26<00:21, 22.87it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 52%|█████▏    | 518/1000 [00:26<00:19, 24.81it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 52%|█████▏    | 524/1000 [00:26<00:18, 25.73it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 53%|█████▎    | 530/1000 [00:26<00:18, 25.99it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 54%|█████▎    | 536/1000 [00:27<00:17, 25.97it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 54%|█████▍    | 542/1000 [00:27<00:17, 26.58it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 55%|█████▍    | 548/1000 [00:27<00:18, 24.92it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 55%|█████▌    | 554/1000 [00:27<00:17, 26.10it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 56%|█████▌    | 560/1000 [00:28<00:17, 25.12it/s]

1.0
1.0
1.0
1.0
1.0


 57%|█████▋    | 566/1000 [00:28<00:16, 26.24it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 57%|█████▋    | 572/1000 [00:28<00:16, 26.29it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 58%|█████▊    | 578/1000 [00:28<00:15, 26.62it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 58%|█████▊    | 584/1000 [00:28<00:15, 26.32it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 59%|█████▉    | 590/1000 [00:29<00:16, 25.17it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 60%|█████▉    | 596/1000 [00:29<00:15, 25.61it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 60%|██████    | 602/1000 [00:29<00:15, 25.30it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 61%|██████    | 608/1000 [00:29<00:15, 25.29it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 61%|██████▏   | 614/1000 [00:30<00:15, 25.50it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 62%|██████▏   | 620/1000 [00:30<00:14, 25.65it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 63%|██████▎   | 626/1000 [00:30<00:14, 26.52it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 63%|██████▎   | 632/1000 [00:30<00:14, 26.24it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 64%|██████▍   | 638/1000 [00:31<00:13, 26.21it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 64%|██████▍   | 644/1000 [00:31<00:13, 26.28it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 65%|██████▌   | 650/1000 [00:31<00:13, 26.48it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 66%|██████▌   | 656/1000 [00:31<00:13, 26.24it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 66%|██████▌   | 662/1000 [00:31<00:12, 26.39it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 66%|██████▋   | 665/1000 [00:32<00:12, 26.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 67%|██████▋   | 674/1000 [00:32<00:12, 26.31it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 68%|██████▊   | 680/1000 [00:32<00:12, 26.55it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 69%|██████▊   | 686/1000 [00:32<00:11, 26.95it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 69%|██████▉   | 692/1000 [00:33<00:11, 27.10it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 70%|██████▉   | 695/1000 [00:33<00:12, 25.27it/s]

1.0
1.0
1.0
1.0
1.0


 70%|███████   | 701/1000 [00:33<00:11, 25.97it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 71%|███████   | 707/1000 [00:33<00:11, 25.77it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 71%|███████▏  | 713/1000 [00:33<00:11, 26.04it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 72%|███████▏  | 719/1000 [00:34<00:10, 26.06it/s]

1.0
1.0
1.0
1.0
1.0
1.0

 72%|███████▎  | 725/1000 [00:34<00:10, 25.39it/s]


1.0
1.0
1.0
1.0
1.0


 73%|███████▎  | 731/1000 [00:34<00:10, 26.16it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 74%|███████▎  | 737/1000 [00:34<00:09, 26.50it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 74%|███████▍  | 743/1000 [00:35<00:09, 26.62it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 75%|███████▍  | 749/1000 [00:35<00:09, 25.46it/s]

1.0
1.0
1.0
1.0
1.0


 76%|███████▌  | 755/1000 [00:35<00:09, 25.79it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 76%|███████▌  | 761/1000 [00:35<00:08, 26.63it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 77%|███████▋  | 767/1000 [00:35<00:08, 26.48it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 77%|███████▋  | 773/1000 [00:36<00:08, 26.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 78%|███████▊  | 779/1000 [00:36<00:08, 25.59it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 78%|███████▊  | 785/1000 [00:36<00:08, 25.89it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 79%|███████▉  | 791/1000 [00:36<00:08, 25.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 80%|███████▉  | 797/1000 [00:37<00:08, 25.34it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 80%|████████  | 800/1000 [00:37<00:08, 24.92it/s]

1.0
1.0
1.0
1.0
1.0


 81%|████████  | 806/1000 [00:37<00:07, 25.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 81%|████████  | 812/1000 [00:37<00:07, 26.42it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 82%|████████▏ | 818/1000 [00:37<00:07, 25.63it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 82%|████████▏ | 824/1000 [00:38<00:07, 24.73it/s]

1.0
1.0
1.0
1.0
1.0


 83%|████████▎ | 830/1000 [00:38<00:06, 24.86it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 84%|████████▎ | 836/1000 [00:38<00:06, 26.07it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 84%|████████▍ | 842/1000 [00:38<00:05, 26.42it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 85%|████████▍ | 848/1000 [00:39<00:05, 26.89it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 85%|████████▌ | 854/1000 [00:39<00:05, 25.00it/s]

1.0
1.0
1.0
1.0
1.0


 86%|████████▌ | 860/1000 [00:39<00:05, 25.97it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 87%|████████▋ | 866/1000 [00:39<00:05, 26.25it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 87%|████████▋ | 872/1000 [00:40<00:04, 26.63it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 88%|████████▊ | 878/1000 [00:40<00:04, 26.37it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 88%|████████▊ | 881/1000 [00:40<00:04, 24.88it/s]

1.0
1.0
1.0
1.0
1.0


 89%|████████▊ | 887/1000 [00:40<00:04, 25.82it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 89%|████████▉ | 893/1000 [00:40<00:04, 26.14it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 90%|████████▉ | 899/1000 [00:41<00:03, 26.47it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 90%|█████████ | 905/1000 [00:41<00:03, 26.56it/s]

1.0
1.0
1.0
1.0
1.0


 91%|█████████ | 911/1000 [00:41<00:03, 25.75it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 92%|█████████▏| 917/1000 [00:41<00:03, 25.60it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 92%|█████████▏| 923/1000 [00:42<00:03, 25.31it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 93%|█████████▎| 929/1000 [00:42<00:02, 24.98it/s]

1.0
1.0
1.0
1.0
1.0


 94%|█████████▎| 935/1000 [00:42<00:02, 23.94it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 94%|█████████▍| 941/1000 [00:42<00:02, 24.57it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 95%|█████████▍| 947/1000 [00:43<00:02, 25.82it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 95%|█████████▌| 953/1000 [00:43<00:01, 26.17it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 96%|█████████▌| 959/1000 [00:43<00:01, 26.60it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 96%|█████████▋| 965/1000 [00:43<00:01, 25.41it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 97%|█████████▋| 971/1000 [00:43<00:01, 26.40it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 98%|█████████▊| 977/1000 [00:44<00:00, 26.33it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 98%|█████████▊| 983/1000 [00:44<00:00, 26.49it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 99%|█████████▊| 986/1000 [00:44<00:00, 26.53it/s]

1.0
1.0
1.0
1.0
1.0


 99%|█████████▉| 992/1000 [00:44<00:00, 25.19it/s]

1.0
1.0
1.0
1.0
1.0
1.0


100%|██████████| 1000/1000 [00:45<00:00, 22.18it/s]

1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [ ]:
print(maxx,epoch)

1.0 121


In [ ]:
#test data
test_data = np.loadtxt( "/content/test.dat" )
test_data.shape

(20000, 9)

In [ ]:
X_test = np.flip(createFeatures(data[:,:-1]))
bias = np.array([1 for i in range(X_test.shape[0])])
Y_test = data[:,-1]
X_test = np.c_[X_test,bias]
Y_test = get_renamed_labels(Y_test)
fin_Xt = khatri_rao(X_test.T,X_test.T)
X_test = khatri_rao(fin_Xt,X_test.T)
X_test = X_test.T
print(X_test.shape,Y_test.shape)

(10000, 729) (10000,)


In [ ]:
new_w = np.zeros((X.shape[1],))
maxx = 0
epoch = 0
for i in tqdm(range(epochs)):
  delw = getCSVMGrad(X,new_w)
  new_w = w - neta*(delw)
  y_t_pred = applySVM(X,new_w)
  y_t_pred = np.where( y_t_pred > 0, 1, -1 )
  av = np.average( y == y_t_pred )
  w=new_w
  print(av)
  if av > maxx:
    epoch = i
    maxx = av
print(maxx)

  0%|          | 3/1000 [00:00<00:43, 22.94it/s]

0.8669
0.9177
0.9426
0.9489
0.9523


  1%|          | 9/1000 [00:00<00:38, 25.43it/s]

0.9387
0.941
0.9443
0.953
0.9696
0.9635


  2%|▏         | 15/1000 [00:00<00:37, 26.20it/s]

0.9706
0.9742
0.9858
0.9917
0.9822
0.9739


  2%|▏         | 21/1000 [00:00<00:36, 27.05it/s]

0.9629
0.9739
0.9826
0.9776
0.977
0.9829


  3%|▎         | 27/1000 [00:01<00:35, 27.14it/s]

0.9953
1.0
1.0
1.0
1.0
1.0


  3%|▎         | 33/1000 [00:01<00:38, 25.27it/s]

1.0
1.0
1.0
1.0
1.0


  4%|▍         | 39/1000 [00:01<00:36, 26.19it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  4%|▍         | 45/1000 [00:01<00:35, 26.61it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  5%|▌         | 51/1000 [00:01<00:35, 26.55it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  6%|▌         | 57/1000 [00:02<00:35, 26.73it/s]

1.0
1.0
1.0
1.0
1.0


  6%|▋         | 63/1000 [00:02<00:36, 26.02it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  7%|▋         | 69/1000 [00:02<00:34, 26.64it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  8%|▊         | 75/1000 [00:02<00:34, 26.79it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  8%|▊         | 81/1000 [00:03<00:33, 27.13it/s]

1.0
1.0
1.0
1.0
1.0
1.0


  8%|▊         | 84/1000 [00:03<00:34, 26.44it/s]

1.0
1.0
1.0
1.0
1.0
1.0

  9%|▉         | 90/1000 [00:03<00:34, 26.06it/s]


1.0
1.0
1.0
1.0
1.0


 10%|▉         | 96/1000 [00:03<00:34, 26.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 10%|█         | 102/1000 [00:03<00:33, 27.05it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 11%|█         | 108/1000 [00:04<00:33, 26.98it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 11%|█▏        | 114/1000 [00:04<00:33, 26.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 12%|█▏        | 120/1000 [00:04<00:33, 26.44it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 13%|█▎        | 126/1000 [00:04<00:32, 26.65it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 13%|█▎        | 132/1000 [00:05<00:32, 26.84it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 14%|█▍        | 138/1000 [00:05<00:32, 26.30it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 14%|█▍        | 144/1000 [00:05<00:32, 26.61it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 15%|█▌        | 150/1000 [00:05<00:31, 27.21it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 16%|█▌        | 156/1000 [00:05<00:31, 27.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 16%|█▌        | 162/1000 [00:06<00:30, 27.58it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 17%|█▋        | 168/1000 [00:06<00:30, 27.67it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 17%|█▋        | 174/1000 [00:06<00:31, 26.29it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 18%|█▊        | 180/1000 [00:06<00:30, 26.84it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 19%|█▊        | 186/1000 [00:07<00:30, 27.04it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 19%|█▉        | 192/1000 [00:07<00:30, 26.71it/s]

1.0
1.0
1.0
1.0
1.0


 20%|█▉        | 198/1000 [00:07<00:32, 25.02it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 20%|██        | 204/1000 [00:07<00:30, 25.93it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 21%|██        | 210/1000 [00:07<00:29, 26.41it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 22%|██▏       | 216/1000 [00:08<00:29, 26.62it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 22%|██▏       | 222/1000 [00:08<00:28, 27.19it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 23%|██▎       | 228/1000 [00:08<00:29, 26.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 23%|██▎       | 234/1000 [00:08<00:28, 26.89it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 24%|██▍       | 240/1000 [00:09<00:27, 27.46it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 25%|██▍       | 246/1000 [00:09<00:27, 27.62it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 25%|██▌       | 252/1000 [00:09<00:28, 26.12it/s]

1.0
1.0
1.0
1.0
1.0


 26%|██▌       | 258/1000 [00:09<00:28, 26.24it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 26%|██▋       | 264/1000 [00:09<00:28, 26.15it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 27%|██▋       | 270/1000 [00:10<00:27, 26.65it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 28%|██▊       | 276/1000 [00:10<00:26, 27.04it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 28%|██▊       | 282/1000 [00:10<00:27, 25.88it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 29%|██▉       | 288/1000 [00:10<00:26, 26.93it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 29%|██▉       | 294/1000 [00:11<00:26, 27.10it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 30%|███       | 300/1000 [00:11<00:25, 27.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 31%|███       | 306/1000 [00:11<00:25, 27.43it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 31%|███       | 309/1000 [00:11<00:26, 26.24it/s]

1.0
1.0
1.0
1.0
1.0


 31%|███       | 312/1000 [00:11<00:28, 24.33it/s]

1.0
1.0
1.0


 32%|███▏      | 318/1000 [00:12<00:33, 20.20it/s]

1.0
1.0
1.0
1.0
1.0


 32%|███▏      | 321/1000 [00:12<00:37, 18.33it/s]

1.0
1.0
1.0


 32%|███▎      | 325/1000 [00:12<00:42, 15.99it/s]

1.0
1.0
1.0


 33%|███▎      | 329/1000 [00:12<00:42, 15.97it/s]

1.0
1.0
1.0
1.0


 33%|███▎      | 332/1000 [00:13<00:37, 17.80it/s]

1.0
1.0
1.0
1.0
1.0


 34%|███▍      | 339/1000 [00:13<00:32, 20.42it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 34%|███▍      | 345/1000 [00:13<00:28, 23.28it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 35%|███▌      | 351/1000 [00:13<00:27, 23.31it/s]

1.0
1.0
1.0
1.0
1.0


 36%|███▌      | 357/1000 [00:14<00:26, 24.61it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 36%|███▋      | 363/1000 [00:14<00:24, 25.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 37%|███▋      | 369/1000 [00:14<00:23, 26.68it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 38%|███▊      | 375/1000 [00:14<00:24, 25.99it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 38%|███▊      | 381/1000 [00:15<00:23, 26.48it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 39%|███▊      | 387/1000 [00:15<00:23, 26.58it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 39%|███▉      | 393/1000 [00:15<00:22, 26.88it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 40%|███▉      | 399/1000 [00:15<00:22, 27.23it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 40%|████      | 405/1000 [00:15<00:22, 26.38it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 41%|████      | 411/1000 [00:16<00:21, 27.17it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 42%|████▏     | 417/1000 [00:16<00:21, 27.34it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 42%|████▏     | 423/1000 [00:16<00:21, 26.82it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 43%|████▎     | 429/1000 [00:16<00:21, 27.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 44%|████▎     | 435/1000 [00:17<00:21, 26.75it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 44%|████▍     | 441/1000 [00:17<00:20, 27.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 45%|████▍     | 447/1000 [00:17<00:20, 26.99it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 45%|████▌     | 453/1000 [00:17<00:20, 26.50it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 46%|████▌     | 459/1000 [00:17<00:20, 26.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 46%|████▋     | 465/1000 [00:18<00:19, 26.76it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 47%|████▋     | 471/1000 [00:18<00:20, 26.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 48%|████▊     | 477/1000 [00:18<00:19, 26.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 48%|████▊     | 483/1000 [00:18<00:19, 26.00it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 49%|████▉     | 489/1000 [00:19<00:19, 25.67it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 50%|████▉     | 495/1000 [00:19<00:19, 26.32it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 50%|█████     | 501/1000 [00:19<00:18, 26.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 51%|█████     | 507/1000 [00:19<00:18, 26.78it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 51%|█████     | 510/1000 [00:19<00:18, 25.86it/s]

1.0
1.0
1.0
1.0
1.0


 52%|█████▏    | 516/1000 [00:20<00:18, 25.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 52%|█████▏    | 522/1000 [00:20<00:18, 25.33it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 53%|█████▎    | 528/1000 [00:20<00:18, 26.14it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 53%|█████▎    | 534/1000 [00:20<00:17, 26.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 54%|█████▍    | 540/1000 [00:21<00:17, 26.33it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 55%|█████▍    | 546/1000 [00:21<00:16, 26.93it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 55%|█████▌    | 552/1000 [00:21<00:16, 27.30it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 56%|█████▌    | 558/1000 [00:21<00:15, 27.71it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 56%|█████▋    | 564/1000 [00:21<00:15, 27.52it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 57%|█████▋    | 570/1000 [00:22<00:16, 26.81it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 58%|█████▊    | 576/1000 [00:22<00:15, 27.09it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 58%|█████▊    | 582/1000 [00:22<00:15, 27.01it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 59%|█████▉    | 588/1000 [00:22<00:15, 26.74it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 59%|█████▉    | 594/1000 [00:23<00:15, 26.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 60%|██████    | 600/1000 [00:23<00:15, 26.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 61%|██████    | 606/1000 [00:23<00:14, 26.83it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 61%|██████    | 612/1000 [00:23<00:14, 27.15it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 62%|██████▏   | 618/1000 [00:23<00:14, 27.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 62%|██████▏   | 624/1000 [00:24<00:14, 26.45it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 63%|██████▎   | 630/1000 [00:24<00:13, 26.62it/s]

1.0
1.0
1.0
1.0
1.0


 64%|██████▎   | 636/1000 [00:24<00:14, 25.40it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 64%|██████▍   | 642/1000 [00:24<00:13, 25.77it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 65%|██████▍   | 648/1000 [00:25<00:13, 25.18it/s]

1.0
1.0
1.0
1.0
1.0


 65%|██████▌   | 654/1000 [00:25<00:13, 26.23it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 66%|██████▌   | 660/1000 [00:25<00:12, 26.92it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 67%|██████▋   | 666/1000 [00:25<00:12, 27.36it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 67%|██████▋   | 672/1000 [00:25<00:11, 27.64it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 68%|██████▊   | 678/1000 [00:26<00:12, 26.29it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 68%|██████▊   | 684/1000 [00:26<00:11, 26.76it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 69%|██████▉   | 690/1000 [00:26<00:11, 26.63it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 70%|██████▉   | 696/1000 [00:26<00:11, 27.13it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 70%|██████▉   | 699/1000 [00:27<00:11, 25.16it/s]

1.0
1.0
1.0
1.0
1.0


 70%|███████   | 705/1000 [00:27<00:11, 25.64it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 71%|███████   | 711/1000 [00:27<00:10, 26.62it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 72%|███████▏  | 717/1000 [00:27<00:10, 26.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 72%|███████▏  | 723/1000 [00:27<00:10, 26.56it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 73%|███████▎  | 729/1000 [00:28<00:10, 26.48it/s]

1.0
1.0
1.0
1.0
1.0


 74%|███████▎  | 735/1000 [00:28<00:10, 25.90it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 74%|███████▍  | 741/1000 [00:28<00:09, 26.87it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 75%|███████▍  | 747/1000 [00:28<00:09, 27.22it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 75%|███████▌  | 753/1000 [00:29<00:09, 26.84it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 76%|███████▌  | 759/1000 [00:29<00:09, 25.29it/s]

1.0
1.0
1.0
1.0
1.0


 76%|███████▋  | 765/1000 [00:29<00:09, 25.97it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 77%|███████▋  | 771/1000 [00:29<00:08, 26.40it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 78%|███████▊  | 777/1000 [00:29<00:08, 26.84it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 78%|███████▊  | 783/1000 [00:30<00:08, 26.57it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 79%|███████▉  | 789/1000 [00:30<00:07, 26.40it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 80%|███████▉  | 795/1000 [00:30<00:07, 26.20it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 80%|████████  | 801/1000 [00:30<00:07, 26.48it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 81%|████████  | 807/1000 [00:31<00:07, 26.64it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 81%|████████▏ | 813/1000 [00:31<00:07, 26.16it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 82%|████████▏ | 819/1000 [00:31<00:06, 26.24it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 82%|████████▎ | 825/1000 [00:31<00:06, 26.89it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 83%|████████▎ | 831/1000 [00:32<00:06, 27.08it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 84%|████████▎ | 837/1000 [00:32<00:05, 27.27it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 84%|████████▍ | 843/1000 [00:32<00:05, 26.87it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 85%|████████▍ | 849/1000 [00:32<00:05, 27.19it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 86%|████████▌ | 855/1000 [00:32<00:05, 27.25it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 86%|████████▌ | 861/1000 [00:33<00:05, 26.74it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 87%|████████▋ | 867/1000 [00:33<00:04, 27.10it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 87%|████████▋ | 873/1000 [00:33<00:04, 26.39it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 88%|████████▊ | 879/1000 [00:33<00:04, 26.54it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 88%|████████▊ | 885/1000 [00:34<00:04, 26.53it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 89%|████████▉ | 891/1000 [00:34<00:04, 26.39it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 90%|████████▉ | 897/1000 [00:34<00:04, 25.17it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 90%|█████████ | 903/1000 [00:34<00:03, 25.56it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 91%|█████████ | 906/1000 [00:34<00:03, 24.49it/s]

1.0
1.0
1.0
1.0
1.0


 91%|█████████ | 912/1000 [00:35<00:03, 24.93it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 92%|█████████▏| 918/1000 [00:35<00:03, 26.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 92%|█████████▏| 924/1000 [00:35<00:02, 25.80it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 93%|█████████▎| 930/1000 [00:35<00:02, 26.89it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 94%|█████████▎| 936/1000 [00:36<00:02, 27.20it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 94%|█████████▍| 942/1000 [00:36<00:02, 26.68it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 95%|█████████▍| 948/1000 [00:36<00:01, 27.13it/s]

1.0
1.0
1.0
1.0
1.0


 95%|█████████▌| 954/1000 [00:36<00:01, 26.26it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 96%|█████████▌| 960/1000 [00:36<00:01, 26.75it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 97%|█████████▋| 966/1000 [00:37<00:01, 26.98it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 97%|█████████▋| 972/1000 [00:37<00:01, 27.33it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 98%|█████████▊| 978/1000 [00:37<00:00, 25.46it/s]

1.0
1.0
1.0
1.0
1.0


 98%|█████████▊| 984/1000 [00:37<00:00, 26.07it/s]

1.0
1.0
1.0
1.0
1.0
1.0


 99%|█████████▉| 990/1000 [00:38<00:00, 26.22it/s]

1.0
1.0
1.0
1.0
1.0
1.0


100%|█████████▉| 996/1000 [00:38<00:00, 26.56it/s]

1.0
1.0
1.0
1.0
1.0
1.0


100%|██████████| 1000/1000 [00:38<00:00, 25.99it/s]

1.0
1.0
1.0
1.0
1.0
